### ISSUE TITLE
a problem about legend 

### ISSUE THREAD

**Issue by Cobbybaby** [boxiangliu/locuscomparer#16]
Hi boxiangliu:
   Thank you for your tool to plot the COLOC, but I have  a problem about the legend, the "r2"  deviate downward. As shown below(I did not change any drawing parameters in LINUX R 3.6.1)：
![1611562572(1)](https://user-images.githubusercontent.com/26817915/105678947-b4b4a400-5f28-11eb-9a6e-db9a54f0f867.jpg)
but it is normal in Windows10. I think this tool should be very good, but I don’t know why this problem occurs. It has troubled me for a long time, so I want to ask you to help me

**Comment by sanghyeonp** [comment]
Can you share the solution that you have found for this?
