### ISSUE TITLE
Compilation failure: no DLL was created

### ISSUE THREAD

**Issue by jccensin** [boxiangliu/locuscomparer#3]
Good morning, 

I would really like to use LocusCompareR as it seems like a great pacakges, but I'm having trouble installing LocusComparer on R 3.5.3 and Windows 10. I can load devtools properly, but when doing 
`devtools::install_github("boxiangliu/locuscomparer")`
I get the following error message after the dependencies have been installed: 

`\* installing *source* package 'locuscomparer' ...
** libs
no DLL was created
ERROR: compilation failed for package 'locuscomparer'
\* removing 'C:/Users/Jenny/Documents/R/win-library/3.5/locuscomparer'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Jenny/AppData/Local/Temp/RtmpWkwypc/file18646fe17717/locuscomparer_1.0.0.tar.gz’ had non-zero exit status`

I've tried other versions of R (3.5.1, 3.4.3), reinstalling Rtools (trying both version 34 and 35), using another computer (same problem), only installing the 32 bit or 64 bit version of R, and I keep getting similar compilation issues. Other packages work fine. I would really appreciate any help in getting it to work. 

Many thanks!

/Jenny

**Comment by boxiangliu** [comment]
Thank you Jenny for reaching out. 

The error message from R console is not immediate clear, so to be honest, I am not sure what is causing the problem. 

Could you try the following: 

1) install rlang (>=0.3.1)
2) install DBI (>=0.10.17)
3) install RMySQL (>=1.0.0)

And then try installing locuscomparer again?

**Comment by boxiangliu** [comment]
Hello Jenny, 

I pushed a fix. Could you reinstall and see if the issue persists?

**Comment by jccensin** [comment]
Hi! 
I'm very sorry for the late reply, I've been away - but the fix worked as a charm! Thank you very much, look forward to using LocusComparer!
