### ISSUE TITLE
Cannot run example code (hangs)

### ISSUE THREAD

**Issue by Jeremy37** [boxiangliu/locuscomparer#6]
Hello,
I've installed locuscomparer successfully as far as I can tell. I have RMySQL installed as well. When I run the example code provided, R simply hangs (for more than 10 min), with no indication that anything is happening.
The example code I'm referring to is:
```
gwas_fn = system.file('extdata','gwas.tsv', package = 'locuscomparer')
eqtl_fn = system.file('extdata','eqtl.tsv', package = 'locuscomparer')
locuscompare(in_fn1 = gwas_fn, in_fn2 = eqtl_fn, title1 = 'CAD GWAS', title2 = 'Coronary Artery eQTL')
```
This happens on my Mac (High Sierra) with RStudio + R 3.6.0, as well as on our unix server. On the server I get the message:
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Can't connect to MySQL server on 'locuscompare-us-west-2a.cvocub39nnri.us-west-2.rds.amazonaws.com' (111)

On my Mac it simply hangs. Any clue as to what is going on?
Thanks!
Jeremy

**Comment by Jeremy37** [comment]
Update: after 10 minutes or so it does produce a plot!  But during that time R is completely frozen and can't be interrupted, only force killed. Does it download or compute full 1000 genomes LD data each time or something?

**Comment by huang-ying** [comment]
Hi Jeremy37

How do you solve the problem? I got the same problem in my linux server. Is the MySQL server still alive?

Failed to connect to database: Error: Can't connect to MySQL server on 'locuscompare-us-west-2a.cvocub39nnri.us-west-2.rds.amazonaws.com' (110)

Thanks.

**Comment by cvalenci** [comment]
HI,
I have the same Issue. I run the example but I only get the plot only contain the variant `rs9349379` on each of the 3 plots. I am running this on a Linux cluster. R version 3.4.4
Thank you

devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                                 
 version  R version 3.4.4 RC (2018-03-09 r74376)
 system   x86_64, linux-gnu                     
 ui       X11                                   
 language (EN)                                  
 collate  en_US.UTF-8                           
 tz       US/Eastern                            
 date     2019-07-05

**Comment by boxiangliu** [comment]
Hello @Jeremy37 @huang-ying @cvalenci. Thank for reaching out. 

I cannot reproduce this error on my own laptop or my server. 

It seems like this issue relates to AWS connectivity. One possibility is that Amazon restricts bandwidth or similar on a region-by-region basis. Could you provide me with your rough geographic location (i.e. New York, Florida) and I can VPN into that region to see what's going on?

**Comment by cvalenci** [comment]
Hi,
Sure, I am located at Baltimore, Maryland.

**Comment by boxiangliu** [comment]
I tried VPNing into multiple locations (Canada, UK, Brazil, Australia) and they all worked fine. So far, I cannot reproduce this error. 

However, I do believe this issue needs to be addressed. I recently had a friend who complained that her work computer cannot access locuscompare, but when she tried to run the same command at home, it worked. So one thing I definitely recommend is to try multiple points of connection. I know this is probably the worst advice and I do apologize for that. 

@Jeremy37 To answer your question, locuscomparer is designed to only retrieve LD information it needs. This mean very little memory footprint and, in theory, should only take a few seconds in most cases (5000 SNPs or less). It is strange it would take 10 minutes.

**Comment by Jeremy37** [comment]
I think that it might a sporadic connection issue. I've run it on our servers, and one day it fails, and the next it works. A bit mysterious.

**Comment by boxiangliu** [comment]
Glad it worked for you :)
