### ISSUE TITLE
Error in function get_lead_snp - in_fn1, in_fn2 are not in scope

### ISSUE THREAD

**Issue by Jeremy37** [boxiangliu/locuscomparer#7]
I got the following error:
"ERROR: Error in sprintf(\"%s not found in the intersection of %s and %s\", snp, : object 'in_fn1' not found\n"

I traced this to the function get_lead_snp, where objects in_fn1 and in_fn2 are used, but are not in scope since they aren't passed in to the function.

**Comment by boxiangliu** [comment]
This error happens when there is no overlap between input files 1 and 2, or because the specified SNP is not in the intersection of these two files. 

Also, thanks for the bug report. It has been fixed.
