### ISSUE TITLE
SNPs with r2 <0.2 are grey, not blue, after latest commit

### ISSUE THREAD

**Issue by jccensin** [boxiangliu/locuscomparer#8]
Hi!

In the latest commit 15 May 2019, the SNPs that are missing in the LD lookup table are coloured grey in the main table, which is great. However, it seems that since SNPs with r2 < 0.2 with the lead SNP are dropped from the LD table, they are also coded as grey. Is there any possibility to update so that SNPs without LD are coded grey and SNPs with r2 0-0.2 are dark blue?

Thank you very much - and thanks for a great software!

Best, 
Jenny

**Comment by boxiangliu** [comment]
Hello Jenny, 

This issue has now been fixed. Thank you for noticing this.
